controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ijamul_controller:
      type: diff_drive_controller/DiffDriveController

    simple_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

ijamul_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    use_stamped_vel: false
    left_wheel_names: ["wheel_left_joint"]
    right_wheel_names: ["wheel_right_joint"]

    publish_rate: 50.0
    pose_covariance_diagonal : [0.001, 0.001, 1.0e-3, 1.0e-3, 1.0e-3, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 1.0e-3, 1.0e-3, 1.0e-3, 0.01]

    wheel_separation: 0.19528
    #wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.033

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    cmd_vel_timeout: 0.5

    
    odom_frame_id: odom
    base_frame_id: base_footprint
    publish_limited_velocity: true

    # pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    # twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    open_loop: true
    enable_odom_tf: true

    # Publish wheel data
    publish_wheel_data: true

   
    # publish_limited_velocity: true
    
    #velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*


    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 0.7  # m/s
        min_velocity           : -0.7 # m/s
        has_acceleration_limits: true
        max_acceleration       : 0.7  # m/s^2
        min_acceleration       : -0.7 # m/s^2
        has_jerk_limits        : false
        max_jerk               : 5.0  # m/s^3
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 8.5  # rad/s
        min_velocity           : -8.5  # rad/s
        has_acceleration_limits: true
        max_acceleration       : 5.0  # rad/s^2
        min_acceleration       : -5.0   # rad/s^2
        has_jerk_limits        : false
        max_jerk               : 2.5  # rad/s^3

simple_velocity_controller:
  ros__parameters:
    joints:
      - wheel_right_joint
      - wheel_left_joint
      